language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t luizparo/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true luizparo/react-test npm test

after_success:
    - docker build -t luizparo/multi-client ./client
    - docker build -t luizparo/multi-nginx ./nginx
    - docker build -t luizparo/multi-server ./server
    - docker build -t luizparo/multi-worker ./worker